// Mocks generated by Mockito 5.4.2 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i37;
import 'dart:typed_data' as _i38;

import 'package:bloc/bloc.dart' as _i27;
import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i11;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i24;
import 'package:ditonton/data/datasources/db/database_helper_tv_series.dart'
    as _i26;
import 'package:ditonton/data/datasources/movie_local_data_source.dart' as _i16;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i14;
import 'package:ditonton/data/datasources/tv_series_local_data_source.dart'
    as _i22;
import 'package:ditonton/data/datasources/tv_series_remote_data_source.dart'
    as _i20;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i15;
import 'package:ditonton/data/models/movie_table.dart' as _i17;
import 'package:ditonton/data/models/tv_series/tv_series_detail_model.dart'
    as _i4;
import 'package:ditonton/data/models/tv_series/tv_series_model.dart' as _i21;
import 'package:ditonton/data/models/tv_series/tv_series_table.dart' as _i23;
import 'package:ditonton/domain/entities/movie.dart' as _i12;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i13;
import 'package:ditonton/domain/entities/tv_series.dart' as _i18;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i19;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i9;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i7;
import 'package:ditonton/domain/usecases/tv_series/get_detail_tv_series.dart'
    as _i28;
import 'package:ditonton/domain/usecases/tv_series/get_on_the_air_tv_series_.dart'
    as _i5;
import 'package:ditonton/domain/usecases/tv_series/get_popular_tv_series.dart'
    as _i29;
import 'package:ditonton/domain/usecases/tv_series/get_status_watchlist_tv_series.dart'
    as _i30;
import 'package:ditonton/domain/usecases/tv_series/get_top_rated_tv_series.dart'
    as _i31;
import 'package:ditonton/domain/usecases/tv_series/get_tv_series_recommendation.dart'
    as _i32;
import 'package:ditonton/domain/usecases/tv_series/get_watchlist_tv_series.dart'
    as _i33;
import 'package:ditonton/domain/usecases/tv_series/remove_watchlist_tv_series.dart'
    as _i34;
import 'package:ditonton/domain/usecases/tv_series/save_watchlist_tv_series.dart'
    as _i35;
import 'package:ditonton/domain/usecases/tv_series/search_tv_series.dart'
    as _i36;
import 'package:ditonton/presentation/bloc/tv_series/tv_series_bloc.dart'
    as _i6;
import 'package:http/http.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i25;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetailModel_2 extends _i1.SmartFake
    implements _i4.TvSeriesDetailModel {
  _FakeTvSeriesDetailModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesOnTheAirUsecase_3 extends _i1.SmartFake
    implements _i5.TvSeriesOnTheAirUsecase {
  _FakeTvSeriesOnTheAirUsecase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesState_4 extends _i1.SmartFake implements _i6.TvSeriesState {
  _FakeTvSeriesState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesRepository_5 extends _i1.SmartFake
    implements _i7.TvSeriesRepository {
  _FakeTvSeriesRepository_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_6 extends _i1.SmartFake implements _i8.Response {
  _FakeResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_7 extends _i1.SmartFake
    implements _i8.StreamedResponse {
  _FakeStreamedResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i9.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>
      getNowPlayingMovies() => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingMovies,
              [],
            ),
            returnValue:
                _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
                    _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
              this,
              Invocation.method(
                #getNowPlayingMovies,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
                _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
                _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, _i13.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i13.MovieDetail>>.value(
                _FakeEither_0<_i11.Failure, _i13.MovieDetail>(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i13.MovieDetail>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getMovieRecommendations,
              [id],
            ),
            returnValue:
                _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
                    _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
              this,
              Invocation.method(
                #getMovieRecommendations,
                [id],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
                _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> saveWatchlist(
          _i13.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [movie],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
            _FakeEither_0<_i11.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [movie],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> removeWatchlist(
          _i13.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
            _FakeEither_0<_i11.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);
  @override
  _i10.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>
      getWatchlistMovies() => (super.noSuchMethod(
            Invocation.method(
              #getWatchlistMovies,
              [],
            ),
            returnValue:
                _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
                    _FakeEither_0<_i11.Failure, List<_i12.Movie>>(
              this,
              Invocation.method(
                #getWatchlistMovies,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i14.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i15.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
        ),
        returnValue:
            _i10.Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]),
      ) as _i10.Future<List<_i15.MovieModel>>);
  @override
  _i10.Future<List<_i15.MovieModel>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i10.Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]),
      ) as _i10.Future<List<_i15.MovieModel>>);
  @override
  _i10.Future<List<_i15.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i10.Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]),
      ) as _i10.Future<List<_i15.MovieModel>>);
  @override
  _i10.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue: _i10.Future<_i3.MovieDetailResponse>.value(
            _FakeMovieDetailResponse_1(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i10.Future<_i3.MovieDetailResponse>);
  @override
  _i10.Future<List<_i15.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [id],
        ),
        returnValue:
            _i10.Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]),
      ) as _i10.Future<List<_i15.MovieModel>>);
  @override
  _i10.Future<List<_i15.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i10.Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]),
      ) as _i10.Future<List<_i15.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i16.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> insertWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<String> removeWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<_i17.MovieTable?> getMovieById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i10.Future<_i17.MovieTable?>.value(),
      ) as _i10.Future<_i17.MovieTable?>);
  @override
  _i10.Future<List<_i17.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue:
            _i10.Future<List<_i17.MovieTable>>.value(<_i17.MovieTable>[]),
      ) as _i10.Future<List<_i17.MovieTable>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i7.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>
      getOnTheAirTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getOnTheAirTvSeries,
              [],
            ),
            returnValue: _i10
                .Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
              this,
              Invocation.method(
                #getOnTheAirTvSeries,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getPopularTvSeries,
              [],
            ),
            returnValue: _i10
                .Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
              this,
              Invocation.method(
                #getPopularTvSeries,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTvSeries,
              [],
            ),
            returnValue: _i10
                .Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
              this,
              Invocation.method(
                #getTopRatedTvSeries,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, _i4.TvSeriesDetailModel>>
      getTvSeriesDetail(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvSeriesDetail,
              [id],
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.Failure, _i4.TvSeriesDetailModel>>.value(
                _FakeEither_0<_i11.Failure, _i4.TvSeriesDetailModel>(
              this,
              Invocation.method(
                #getTvSeriesDetail,
                [id],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, _i4.TvSeriesDetailModel>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>
      getTvSeriesRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvSeriesRecommendations,
              [id],
            ),
            returnValue: _i10
                .Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
              this,
              Invocation.method(
                #getTvSeriesRecommendations,
                [id],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>> searchSeries(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSeries,
          [query],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
          this,
          Invocation.method(
            #searchSeries,
            [query],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> saveWatchlist(
          _i19.TvSeriesDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [movie],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
            _FakeEither_0<_i11.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [movie],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> removeWatchlist(
          _i19.TvSeriesDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
            _FakeEither_0<_i11.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);
  @override
  _i10.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>
      getWatchlistTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getWatchlistTvSeries,
              [],
            ),
            returnValue: _i10
                .Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
              this,
              Invocation.method(
                #getWatchlistTvSeries,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i20.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i21.TvSeriesModel>> getOnTheAirTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvSeries,
          [],
        ),
        returnValue:
            _i10.Future<List<_i21.TvSeriesModel>>.value(<_i21.TvSeriesModel>[]),
      ) as _i10.Future<List<_i21.TvSeriesModel>>);
  @override
  _i10.Future<List<_i21.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvSeries,
          [],
        ),
        returnValue:
            _i10.Future<List<_i21.TvSeriesModel>>.value(<_i21.TvSeriesModel>[]),
      ) as _i10.Future<List<_i21.TvSeriesModel>>);
  @override
  _i10.Future<List<_i21.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvSeries,
          [],
        ),
        returnValue:
            _i10.Future<List<_i21.TvSeriesModel>>.value(<_i21.TvSeriesModel>[]),
      ) as _i10.Future<List<_i21.TvSeriesModel>>);
  @override
  _i10.Future<_i4.TvSeriesDetailModel> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue: _i10.Future<_i4.TvSeriesDetailModel>.value(
            _FakeTvSeriesDetailModel_2(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i10.Future<_i4.TvSeriesDetailModel>);
  @override
  _i10.Future<List<_i21.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesRecommendations,
          [id],
        ),
        returnValue:
            _i10.Future<List<_i21.TvSeriesModel>>.value(<_i21.TvSeriesModel>[]),
      ) as _i10.Future<List<_i21.TvSeriesModel>>);
  @override
  _i10.Future<List<_i21.TvSeriesModel>> searchSeries(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSeries,
          [query],
        ),
        returnValue:
            _i10.Future<List<_i21.TvSeriesModel>>.value(<_i21.TvSeriesModel>[]),
      ) as _i10.Future<List<_i21.TvSeriesModel>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i22.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> insertWatchlist(_i23.TvSeriesTable? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [series],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<String> removeWatchlist(_i23.TvSeriesTable? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [series],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<_i23.TvSeriesTable?> getSeriesById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeriesById,
          [id],
        ),
        returnValue: _i10.Future<_i23.TvSeriesTable?>.value(),
      ) as _i10.Future<_i23.TvSeriesTable?>);
  @override
  _i10.Future<List<_i23.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvSeries,
          [],
        ),
        returnValue:
            _i10.Future<List<_i23.TvSeriesTable>>.value(<_i23.TvSeriesTable>[]),
      ) as _i10.Future<List<_i23.TvSeriesTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i24.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i25.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i10.Future<_i25.Database?>.value(),
      ) as _i10.Future<_i25.Database?>);
  @override
  _i10.Future<int> insertWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);
  @override
  _i10.Future<int> removeWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);
  @override
  _i10.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i10.Future<Map<String, dynamic>?>.value(),
      ) as _i10.Future<Map<String, dynamic>?>);
  @override
  _i10.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i10.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvSeriesDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDatabaseHelper extends _i1.Mock
    implements _i26.TvSeriesDatabaseHelper {
  MockTvSeriesDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i25.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i10.Future<_i25.Database?>.value(),
      ) as _i10.Future<_i25.Database?>);
  @override
  _i10.Future<int> insertWatchlist(_i23.TvSeriesTable? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [series],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);
  @override
  _i10.Future<int> removeWatchlist(_i23.TvSeriesTable? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [series],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);
  @override
  _i10.Future<Map<String, dynamic>?> getSeriesById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeriesById,
          [id],
        ),
        returnValue: _i10.Future<Map<String, dynamic>?>.value(),
      ) as _i10.Future<Map<String, dynamic>?>);
  @override
  _i10.Future<List<Map<String, dynamic>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvSeries,
          [],
        ),
        returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i10.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [OnTheAirTvSeriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTvSeriesBloc extends _i1.Mock
    implements _i6.OnTheAirTvSeriesBloc {
  MockOnTheAirTvSeriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesOnTheAirUsecase get tvSeriesOnTheAirUsecase =>
      (super.noSuchMethod(
        Invocation.getter(#tvSeriesOnTheAirUsecase),
        returnValue: _FakeTvSeriesOnTheAirUsecase_3(
          this,
          Invocation.getter(#tvSeriesOnTheAirUsecase),
        ),
      ) as _i5.TvSeriesOnTheAirUsecase);
  @override
  _i6.TvSeriesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTvSeriesState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.TvSeriesState);
  @override
  _i10.Stream<_i6.TvSeriesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i10.Stream<_i6.TvSeriesState>.empty(),
      ) as _i10.Stream<_i6.TvSeriesState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  void add(_i6.TvSeriesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i6.TvSeriesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i6.TvSeriesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i6.TvSeriesEvent>(
    _i27.EventHandler<E, _i6.TvSeriesState>? handler, {
    _i27.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i27.Transition<_i6.TvSeriesEvent, _i6.TvSeriesState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  void onChange(_i27.Change<_i6.TvSeriesState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TvSeriesDetailUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailUsecase extends _i1.Mock
    implements _i28.TvSeriesDetailUsecase {
  MockTvSeriesDetailUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.TvSeriesRepository get tvSeriesRepository => (super.noSuchMethod(
        Invocation.getter(#tvSeriesRepository),
        returnValue: _FakeTvSeriesRepository_5(
          this,
          Invocation.getter(#tvSeriesRepository),
        ),
      ) as _i7.TvSeriesRepository);
  @override
  _i10.Future<_i2.Either<_i11.Failure, _i19.TvSeriesDetail>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i19.TvSeriesDetail>>.value(
                _FakeEither_0<_i11.Failure, _i19.TvSeriesDetail>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i19.TvSeriesDetail>>);
}

/// A class which mocks [TvSeriesOnTheAirUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesOnTheAirUsecase extends _i1.Mock
    implements _i5.TvSeriesOnTheAirUsecase {
  MockTvSeriesOnTheAirUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.TvSeriesRepository get tvSeriesRepository => (super.noSuchMethod(
        Invocation.getter(#tvSeriesRepository),
        returnValue: _FakeTvSeriesRepository_5(
          this,
          Invocation.getter(#tvSeriesRepository),
        ),
      ) as _i7.TvSeriesRepository);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
}

/// A class which mocks [TvSeriesPopularUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesPopularUsecase extends _i1.Mock
    implements _i29.TvSeriesPopularUsecase {
  MockTvSeriesPopularUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.TvSeriesRepository get tvSeriesRepository => (super.noSuchMethod(
        Invocation.getter(#tvSeriesRepository),
        returnValue: _FakeTvSeriesRepository_5(
          this,
          Invocation.getter(#tvSeriesRepository),
        ),
      ) as _i7.TvSeriesRepository);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
}

/// A class which mocks [GetStatusWatchlistTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStatusWatchlistTvSeries extends _i1.Mock
    implements _i30.GetStatusWatchlistTvSeries {
  MockGetStatusWatchlistTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
}

/// A class which mocks [TvSeriesTopRatedUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesTopRatedUsecase extends _i1.Mock
    implements _i31.TvSeriesTopRatedUsecase {
  MockTvSeriesTopRatedUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.TvSeriesRepository get tvSeriesRepository => (super.noSuchMethod(
        Invocation.getter(#tvSeriesRepository),
        returnValue: _FakeTvSeriesRepository_5(
          this,
          Invocation.getter(#tvSeriesRepository),
        ),
      ) as _i7.TvSeriesRepository);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
}

/// A class which mocks [GettvSeriesRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGettvSeriesRecommendations extends _i1.Mock
    implements _i32.GettvSeriesRecommendations {
  MockGettvSeriesRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.TvSeriesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvSeriesRepository_5(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i7.TvSeriesRepository);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>> execute(
          dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
}

/// A class which mocks [GetWatchlistTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvSeries extends _i1.Mock
    implements _i33.GetWatchlistTvSeries {
  MockGetWatchlistTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
}

/// A class which mocks [RemoveWatchlistTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTvSeries extends _i1.Mock
    implements _i34.RemoveWatchlistTvSeries {
  MockRemoveWatchlistTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> execute(
          _i19.TvSeriesDetail? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [series],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
            _FakeEither_0<_i11.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [series],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);
}

/// A class which mocks [SaveWatchlistTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTvSeries extends _i1.Mock
    implements _i35.SaveWatchlistTvSeries {
  MockSaveWatchlistTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> execute(
          _i19.TvSeriesDetail? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [series],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, String>>.value(
            _FakeEither_0<_i11.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [series],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, String>>);
}

/// A class which mocks [SearchTvSeriesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTvSeriesUsecase extends _i1.Mock
    implements _i36.SearchTvSeriesUsecase {
  MockSearchTvSeriesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.TvSeriesRepository get tvSeriesRepository => (super.noSuchMethod(
        Invocation.getter(#tvSeriesRepository),
        returnValue: _FakeTvSeriesRepository_5(
          this,
          Invocation.getter(#tvSeriesRepository),
        ),
      ) as _i7.TvSeriesRepository);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>> execute(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [query],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>.value(
                _FakeEither_0<_i11.Failure, List<_i18.TvSeries>>(
          this,
          Invocation.method(
            #execute,
            [query],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i18.TvSeries>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i8.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i8.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i37.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i37.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i37.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);
  @override
  _i10.Future<_i8.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i37.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);
  @override
  _i10.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<_i38.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<_i38.Uint8List>.value(_i38.Uint8List(0)),
      ) as _i10.Future<_i38.Uint8List>);
  @override
  _i10.Future<_i8.StreamedResponse> send(_i8.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i10.Future<_i8.StreamedResponse>.value(_FakeStreamedResponse_7(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i10.Future<_i8.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
